parser: "@typescript-eslint/parser"
env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
plugins:
  - simple-import-sort
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
